version: "3.8"

services:
  bot:
    container_name: springbattlebot-bot
    build:
      context: bot
      dockerfile: Dockerfile.prod
    image: bot
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - ./bot/.env
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: springbattlebot-db
    image: postgres:14.1
    expose:
      - 5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d database -U username"]
      interval: 1s
      timeout: 1s
      retries: 30
